### ISSUE TITLE
ReferenceErr: err not defined

### ISSUE THREAD

**Issue by ychennay** [mradamlacey/json-to-es-bulk#2]
I have followed the instructions within the README.MD, and issued the following command:

`json-to-es-bulk yuchen$ node index.js -f data.json --index test --type test
`

Where data.json is my input file and contains a field called `id`. However, I immediately get the error in the issue title.

**Comment by mradamlacey** [comment]
Just pushed a commit that fixes the error handling.  Can you look at your input file and make sure it's a valid JSON file that contains an array of data?

**Comment by ychennay** [comment]
Works great now. Appreciate the quick fix. 

FYI, I ended up writing my own adhoc script with NodeJS after opening this issue since it was a time-sensitive task, and after checking out your `index.js` realized your version is definitely much better! Thanks for making this.
